### ISSUE TITLE
Accept a list of removed repos

### ISSUE THREAD

**Issue by davide-esr** [elektronenhirn/oper-delta#1]
It's already somehow possible to filter out removed repos because they don't have any of the branches.
But, this is not 100% reliable, because there can be places where we just forgot to create the branches.
It would be nice to be able to feed oper an "approved" list of removed repos, that can then securely filtered out.

I guess the best way to provide the list would be with a file containing paths or project names.

**Comment by davide-esr** [comment]
Also useful for excluding repos where develop branches were created, but that were then excluded, like the rse22 device makefiles.

**Comment by elektronenhirn** [comment]
See new cmd line option

--repo-ignore-list <path>    path to file which contains list of repos to ignore

The file format is the same as .repo/project.list
