### ISSUE TITLE
false positive external/mdnsresponder

### ISSUE THREAD

**Issue by davide-esr** [elektronenhirn/oper-delta#3]
The origin/idc-qcom-develop branch is listed not consolidated and not fast forwardable.
To me, it looks fast-forwardable

**Comment by davide-esr** [comment]
same in frameworks/base and frameworks/native.
note: in all of these repos, there is also a -mod branch that is not forwardable at the moment.

**Comment by davide-esr** [comment]
system/connectivity/wificond also has a false positive on origin/idc-qcom-develop
Here there is also a -mod branch, but in this case the -mod branch is ready

same in system/sepolicy

**Comment by davide-esr** [comment]
Well now I get it, it was quite stupid of me to not realize this.

You always check against HEAD, which is mostly good.

When there is a -mod branch, HEAD is -mod-qcom-mainline and we correctly check -mod-qcom-develop against it.
But, we still check -qcom-mainline, and we should check it against -qcom-develop, not against HEAD. Of course -qcom-develop will never have -mod-qcom-mainline as an ancestor.

So, the way we check the fast-forwardability is good, but we need to refine which SHAs we check

**Comment by nsndvd** [comment]
I think you can close this.. my initial consideration arose from a wrong understanding of how oper-delta is supposed to work.

**Comment by elektronenhirn** [comment]
ok
